services:
  myapp:
    build: .
    volumes:
      - ./samples/:/samples/
      - ./app:/app
      - ./intro/:/intro/
      - ./outro/:/outro/
      - ./delimiter/:/delimiter/
      - ./result/:/result/
